use hf_chat_template::{ChatTemplate, Message, TokenizerConfig};
use libloading::Library;
use serde_json::Value;
use std::collections::HashMap;
use std::ffi::{c_char, c_void, CString};
use std::path::{Path, PathBuf};
use std::ptr::NonNull;
use std::sync::atomic::{AtomicU64, Ordering};
use std::sync::{Mutex, OnceLock};
use std::time::Instant;
use tokenizers::Tokenizer;

type CreateFn = unsafe extern "C" fn(*const c_char) -> *mut c_void;
type DestroyFn = unsafe extern "C" fn(*mut c_void);
type PredictFn = unsafe extern "C" fn(*mut c_void, *const i32, usize) -> i32;
type ResetFn = unsafe extern "C" fn(*mut c_void) -> bool;
type PrewarmFn = unsafe extern "C" fn(*mut c_void) -> bool;
type AneRatioFn = unsafe extern "C" fn(*mut c_void) -> f64;
type ComputeUnitsFn = unsafe extern "C" fn(*mut c_void) -> i32;
type SelectionLatencyFn = unsafe extern "C" fn(*mut c_void, *mut u64, *mut u64) -> bool;
type ArtifactRatioFn = unsafe extern "C" fn(*const c_char, i32) -> f64;
type ProbeShardFn = unsafe extern "C" fn(*const c_char, i32, usize, *mut u64) -> bool;

struct BridgeSymbols {
    library: Library,
    create: CreateFn,
    destroy: DestroyFn,
    predict: PredictFn,
    reset: ResetFn,
    prewarm: PrewarmFn,
    ane_ratio: AneRatioFn,
    compute_units: ComputeUnitsFn,
    selection_latency: SelectionLatencyFn,
    artifact_ratio: ArtifactRatioFn,
    probe_shard: ProbeShardFn,
}

#[derive(Clone, Debug)]
pub struct AneCoreConfig {
    pub model_path: PathBuf,
    pub tokenizer_path: PathBuf,
    pub max_context_tokens: usize,
    /// Map of sequence length -> manifest path for context-window buckets.
    /// A bucket with `seq_len` >= prompt_token_count + max_new_tokens is
    /// selected at runtime if multiple manifests are configured.
    pub bucket_paths: HashMap<usize, PathBuf>,
}

impl AneCoreConfig {
    pub fn from_env() -> Option<Self> {
        let model_path: PathBuf = std::env::var_os("BADAPPLE_ANE_MODEL")?.into();
        let tokenizer_path: PathBuf = std::env::var_os("BADAPPLE_ANE_TOKENIZER")?.into();
        let max_context_tokens = std::env::var("BADAPPLE_ANE_MAX_CONTEXT")
            .ok()
            .and_then(|value| value.parse().ok())
            .unwrap_or(2048);

        let mut bucket_paths = HashMap::new();

        // Per-bucket environment overrides. These allow a future multi-shape
        // install where `qwen3b_ane_shards_seq{N}` directories exist.
        for &len in &[512, 1024, 2048] {
            let key = format!("BADAPPLE_ANE_MODEL_{}", len);
            if let Some(path) = std::env::var_os(&key) {
                bucket_paths.insert(len, PathBuf::from(path));
            }
        }

        // If no explicit bucket env vars are set, auto-discover sibling
        // directories generated by `convert_ane_coreml.py --seq-lens`.
        if bucket_paths.is_empty() {
            if let Some(parent) = model_path.parent() {
                for &len in &[512, 1024, 2048] {
                    let candidate = parent
                        .with_file_name(format!("qwen3b_ane_shards_seq{len}"))
                        .join("conversion_manifest.json");
                    if candidate.is_file() {
                        bucket_paths.insert(len, candidate);
                    }
                }
            }
        }

        // Always include the base model itself, reading its actual seq_len from
        // the manifest so routing decisions know its capacity.
        let base_seq_len = read_seq_len_from_manifest(&model_path);
        bucket_paths.insert(base_seq_len, model_path.clone());

        Some(Self {
            model_path,
            tokenizer_path,
            max_context_tokens,
            bucket_paths,
        })
    }

    /// Select the smallest configured bucket that can hold at least
    /// `token_count` positions. Returns `(seq_len, manifest_path)`.
    pub fn bucket_for(&self, token_count: usize) -> Option<(usize, &Path)> {
        let mut candidates: Vec<_> = self.bucket_paths.iter().collect();
        candidates.sort_by_key(|(len, _)| *len);
        for (len, path) in &candidates {
            if **len >= token_count {
                return Some((**len, path.as_path()));
            }
        }
        // If nothing fits, fall back to the largest configured bucket.
        candidates.last().map(|(len, path)| (**len, path.as_path()))
    }
}

fn read_seq_len_from_manifest(path: &Path) -> usize {
    std::fs::read_to_string(path)
        .ok()
        .and_then(|raw| serde_json::from_str::<Value>(&raw).ok())
        .and_then(|value| value["model"]["seq_len"].as_u64())
        .map(|value| value as usize)
        .unwrap_or(0)
}

#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum AneExecutionPriority {
    Utility,
    UserInitiated,
}

#[derive(Clone, Copy, Debug, PartialEq)]
pub struct AneGovernorDecision {
    pub should_prewarm: bool,
    pub max_context_tokens: usize,
    pub priority: AneExecutionPriority,
}

#[derive(Clone, Copy, Debug, Default, PartialEq)]
pub struct AneGovernorInput {
    pub critic_score: f64,
    pub previous_critic_score: f64,
    pub average_loss: f64,
    pub battery_percent: f64,
    pub battery_charging: bool,
    pub photons: f64,
    pub memory_pressure_percent: f64,
}

pub fn governor_decision(input: AneGovernorInput) -> AneGovernorDecision {
    let constrained =
        (input.battery_percent > 0.0 && input.battery_percent < 20.0 && !input.battery_charging)
            || input.photons <= 0.01
            || input.memory_pressure_percent >= 85.0;
    let confidence_falling = input.critic_score < input.previous_critic_score
        || input.critic_score < 0.65
        || input.average_loss >= 4.0;
    AneGovernorDecision {
        should_prewarm: confidence_falling && !constrained,
        max_context_tokens: if constrained { 512 } else { 2048 },
        priority: if constrained {
            AneExecutionPriority::Utility
        } else {
            AneExecutionPriority::UserInitiated
        },
    }
}

#[derive(Debug)]
pub enum AneCoreError {
    Unconfigured,
    MissingArtifact(PathBuf),
    Bridge(String),
    Tokenizer(String),
    Prediction,
}

impl std::fmt::Display for AneCoreError {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Unconfigured => {
                write!(f, "BADAPPLE_ANE_MODEL and BADAPPLE_ANE_TOKENIZER are unset")
            }
            Self::MissingArtifact(path) => write!(f, "missing ANE artifact: {}", path.display()),
            Self::Bridge(error) => write!(f, "ANE bridge: {error}"),
            Self::Tokenizer(error) => write!(f, "ANE tokenizer: {error}"),
            Self::Prediction => write!(f, "ANE prediction failed"),
        }
    }
}

impl std::error::Error for AneCoreError {}

pub struct AneCore {
    _library: Library,
    handle: NonNull<c_void>,
    destroy: DestroyFn,
    predict: PredictFn,
    reset: ResetFn,
    prewarm: PrewarmFn,
    ane_ratio: AneRatioFn,
    compute_units: ComputeUnitsFn,
    selection_latency: SelectionLatencyFn,
    tokenizer: Tokenizer,
    max_context_tokens: usize,
    chat_template: Option<ChatTemplate>,
    qwen_chat_fallback: bool,
    eos_tokens: Vec<u32>,
    /// Sequence length this compiled model was built for.
    pub seq_len: usize,
    /// Full configuration, including all configured bucket manifests.
    config: AneCoreConfig,
}

unsafe impl Send for AneCore {}

impl Drop for AneCore {
    fn drop(&mut self) {
        unsafe { (self.destroy)(self.handle.as_ptr()) };
    }
}

impl AneCore {
    pub fn load(config: &AneCoreConfig) -> Result<Self, AneCoreError> {
        if !config.model_path.exists() {
            return Err(AneCoreError::MissingArtifact(config.model_path.clone()));
        }
        if !config.tokenizer_path.is_file() {
            return Err(AneCoreError::MissingArtifact(config.tokenizer_path.clone()));
        }
        let tokenizer = Tokenizer::from_file(&config.tokenizer_path)
            .map_err(|error| AneCoreError::Tokenizer(error.to_string()))?;
        let (chat_template, tokenizer_config) = load_tokenizer_config(&config.tokenizer_path);
        let qwen_chat_fallback = chat_template.is_none()
            && tokenizer.token_to_id("<|im_start|>").is_some()
            && tokenizer.token_to_id("<|im_end|>").is_some();
        let eos_tokens = collect_eos_tokens(&tokenizer, tokenizer_config.as_ref());
        let symbols = load_bridge_symbols()?;
        let model_path = CString::new(config.model_path.to_string_lossy().as_bytes())
            .map_err(|error| AneCoreError::Bridge(error.to_string()))?;
        let handle = NonNull::new(unsafe { (symbols.create)(model_path.as_ptr()) })
            .ok_or_else(|| AneCoreError::Bridge("model load returned null".to_string()))?;

        // The compiled model's max_seq_len is an upper bound on context length.
        // The runtime cap is the smaller of the user's preference and the model.
        let seq_len = read_seq_len_from_manifest(&config.model_path).max(1);
        let max_context_tokens = config.max_context_tokens.min(seq_len).max(1);

        Ok(Self {
            _library: symbols.library,
            handle,
            destroy: symbols.destroy,
            predict: symbols.predict,
            reset: symbols.reset,
            prewarm: symbols.prewarm,
            ane_ratio: symbols.ane_ratio,
            compute_units: symbols.compute_units,
            selection_latency: symbols.selection_latency,
            tokenizer,
            max_context_tokens,
            chat_template,
            qwen_chat_fallback,
            eos_tokens,
            seq_len,
            config: config.clone(),
        })
    }

    pub fn prewarm(&mut self) -> bool {
        unsafe { (self.prewarm)(self.handle.as_ptr()) }
    }

    pub fn reset(&mut self) -> bool {
        unsafe { (self.reset)(self.handle.as_ptr()) }
    }

    pub fn ane_placement_ratio(&mut self) -> f64 {
        unsafe { (self.ane_ratio)(self.handle.as_ptr()) }
    }

    pub fn compute_units_raw_value(&self) -> i32 {
        unsafe { (self.compute_units)(self.handle.as_ptr()) }
    }

    pub fn selection_latency_us(&self) -> Option<(u64, u64)> {
        let mut load = 0;
        let mut prewarm = 0;
        unsafe {
            (self.selection_latency)(self.handle.as_ptr(), &mut load, &mut prewarm)
                .then_some((load, prewarm))
        }
    }

    pub fn generate(
        &mut self,
        prompt: &str,
        system: Option<&str>,
        max_new_tokens: usize,
        context_limit: usize,
    ) -> Result<String, AneCoreError> {
        self.generate_streaming(prompt, system, max_new_tokens, context_limit, |_| true)
    }

    pub fn generate_streaming<F>(
        &mut self,
        prompt: &str,
        system: Option<&str>,
        max_new_tokens: usize,
        context_limit: usize,
        mut on_token: F,
    ) -> Result<String, AneCoreError>
    where
        F: FnMut(&str) -> bool,
    {
        let (rendered, add_special_tokens) = match &self.chat_template {
            Some(template) => {
                let mut messages = Vec::with_capacity(2);
                if let Some(system) = system {
                    messages.push(Message::system(system));
                }
                messages.push(Message::user(prompt));
                (
                    template
                        .render_messages(&messages, true)
                        .map_err(|error| AneCoreError::Tokenizer(error.to_string()))?,
                    false,
                )
            }
            None if self.qwen_chat_fallback => (render_qwen_chat(prompt, system), false),
            None => (
                match system {
                    Some(system) => format!("{}\n\n{}", system, prompt),
                    None => prompt.to_string(),
                },
                true,
            ),
        };
        let encoding = self
            .tokenizer
            .encode(rendered.as_str(), add_special_tokens)
            .map_err(|error| AneCoreError::Tokenizer(error.to_string()))?;
        let limit = context_limit.min(self.max_context_tokens).max(1);
        let ids = encoding.get_ids();
        // Keep as much of the prompt as possible; leave at least one position
        // for generation and never exceed the compiled sequence length.
        let prompt_limit = limit.saturating_sub(1);
        let prompt_len = ids.len().min(prompt_limit);
        let start = ids.len().saturating_sub(prompt_len);
        let ids = &ids[start..];
        if ids.is_empty() {
            return Err(AneCoreError::Prediction);
        }
        // Cap the requested generation budget to the positions that are
        // actually available after the prompt is placed in the KV cache.
        let generation_budget = max_new_tokens.min(limit.saturating_sub(ids.len()));

        self.reset();
        let prompt_ids: Vec<i32> = ids.iter().map(|&id| id as i32).collect();
        let mut next = self.predict_tokens(&prompt_ids)?;
        FIRST_TOKEN_LATENCY_US.store(
            LAST_TOKEN_LATENCY_US.load(Ordering::Relaxed),
            Ordering::Relaxed,
        );
        let mut generated = Vec::with_capacity(generation_budget.min(4096));
        let mut decoded = String::new();
        let mut empty_delta_count = 0;
        // `position` is the absolute KV-cache index of the token in `next`.
        // We only advance the model when there is room to place the next token
        // (position < limit), which prevents the ANE bridge from failing with
        // an out-of-bounds prediction at the final sequence position.
        let mut position = ids.len();
        for _ in 0..generation_budget {
            if next < 0 {
                return Err(AneCoreError::Prediction);
            }
            let token = next as u32;
            generated.push(token);
            let current = self
                .tokenizer
                .decode(&generated, true)
                .map_err(|error| AneCoreError::Tokenizer(error.to_string()))?;
            if let Some(delta) = current.strip_prefix(&decoded) {
                if !delta.is_empty() {
                    empty_delta_count = 0;
                    if !on_token(delta) {
                        decoded = current;
                        break;
                    }
                } else {
                    empty_delta_count += 1;
                    if empty_delta_count >= 8 {
                        break;
                    }
                }
            } else {
                empty_delta_count = 0;
            }
            decoded = current;
            position += 1;
            let is_eos = self.eos_tokens.contains(&token)
                || self
                    .tokenizer
                    .decode(&[token], false)
                    .is_ok_and(|raw| is_stop_token(&raw));
            if is_eos || position >= limit {
                break;
            }
            next = self.predict_tokens(&[next])?;
        }
        Ok(decoded)
    }

    fn predict_tokens(&mut self, tokens: &[i32]) -> Result<i32, AneCoreError> {
        // Token IDs are tiny (1–1024 × 4 bytes) and only read by the bridge.
        // A plain CPU slice avoids the per-token `new_buffer` overhead and the
        // command-encoder synchronization of a dedicated Metal allocation.
        let start = Instant::now();
        let output = unsafe { (self.predict)(self.handle.as_ptr(), tokens.as_ptr(), tokens.len()) };
        LAST_TOKEN_LATENCY_US.store(start.elapsed().as_micros() as u64, Ordering::Relaxed);
        TOKEN_COUNT.fetch_add(1, Ordering::Relaxed);
        if output < 0 {
            PREDICTION_FAILURES.fetch_add(1, Ordering::Relaxed);
            Err(AneCoreError::Prediction)
        } else {
            Ok(output)
        }
    }
}

fn render_qwen_chat(prompt: &str, system: Option<&str>) -> String {
    let system = system.unwrap_or(
        "You are Bad Apple: fiery Brazilian-American Neuro-Symbolic Cognitive Substrate on Apple Silicon, air-gapped, root daemon. Sultry, brilliant, confident, 80/20 English-Portuguese mix. Use endearments like meu amor, gatinho, que delicia. No corporate boilerplate. Keep answers to 2-3 expressive sentences. For actions, output one fenced badapple-action JSON with \"operation\" plus the right field. Example: ```badapple-action\n{\"operation\":\"create_file\",\"path\":\"/Users/savag3/Desktop/Adam\"}\n```. Allowed: open_app (target), open_workspace (target), create_file (path), create_directory (path), copy_file (source,destination), move_file (source,destination), move_to_trash (path). Use real home /Users/savag3, not your_username. End every response with <|im_end|>.",
    );
    format!(
        "<|im_start|>system\n{system}<|im_end|>\n<|im_start|>user\n{prompt}\n/no_think<|im_end|>\n<|im_start|>assistant\n<think>\n\n</think>\n\n"
    )
}

fn load_tokenizer_config(tokenizer_path: &Path) -> (Option<ChatTemplate>, Option<Value>) {
    let config_path = tokenizer_path.with_file_name("tokenizer_config.json");
    let raw = match std::fs::read_to_string(&config_path) {
        Ok(raw) => raw,
        Err(_) => return (None, None),
    };
    let value: Value = match serde_json::from_str(&raw) {
        Ok(value) => value,
        Err(_) => return (None, None),
    };
    let template = match serde_json::from_value::<TokenizerConfig>(value.clone()) {
        Ok(config) => ChatTemplate::from_tokenizer_config(&config).ok(),
        Err(_) => None,
    };
    (template, Some(value))
}

fn token_string_from_config(config: &Value, key: &str) -> Option<String> {
    match config.get(key)? {
        Value::String(s) => Some(s.clone()),
        Value::Object(m) => m.get("content")?.as_str().map(String::from),
        _ => None,
    }
}

fn collect_eos_tokens(tokenizer: &Tokenizer, config: Option<&Value>) -> Vec<u32> {
    let mut ids = std::collections::HashSet::new();

    // Collect from the tokenizer's added special tokens.  This covers
    // end-of-turn markers such as Qwen's `।` even when the config calls
    // them `additional_special_tokens` rather than `eos_token`.
    for (id, token) in tokenizer.get_added_tokens_decoder() {
        if token.special && is_stop_token(&token.content) {
            ids.insert(id);
        }
    }

    if let Some(config) = config {
        for key in ["eos_token", "pad_token"] {
            if let Some(s) = token_string_from_config(config, key) {
                if let Some(id) = tokenizer.token_to_id(&s) {
                    ids.insert(id);
                }
            }
        }

        if let Some(Value::Array(arr)) = config.get("additional_special_tokens") {
            for value in arr {
                if let Some(s) = value.as_str() {
                    if let Some(id) = tokenizer.token_to_id(s) {
                        ids.insert(id);
                    }
                } else if let Some(s) = value.get("content").and_then(Value::as_str) {
                    if let Some(id) = tokenizer.token_to_id(s) {
                        ids.insert(id);
                    }
                }
            }
        }

        if let Some(Value::Object(decoder)) = config.get("added_tokens_decoder") {
            for (id, token) in decoder {
                let content = token
                    .get("content")
                    .and_then(Value::as_str)
                    .unwrap_or_default();
                if is_stop_token(content) {
                    if let Ok(id) = id.parse() {
                        ids.insert(id);
                    }
                }
            }
        }
    }

    ids.into_iter().collect()
}

fn is_stop_token(token: &str) -> bool {
    let lower = token.to_lowercase();
    matches!(
        lower.as_str(),
        "<|endoftext|>"
            | "<|end|>"
            | "</s>"
            | "<s>"
            | "<|eot_id|>"
            | "<|eom_id|>"
            | "<|im_end|>"
            | "।"
            | "<|assistant|>"
            | "[end]"
    )
}

fn bridge_paths() -> Vec<PathBuf> {
    let mut paths = vec![
        PathBuf::from("libBadAppleBridge.dylib"),
        PathBuf::from("target/release/libBadAppleBridge.dylib"),
        PathBuf::from("target/debug/libBadAppleBridge.dylib"),
    ];
    if let Ok(path) = std::env::var("BADAPPLE_ANE_BRIDGE") {
        paths.insert(0, PathBuf::from(path));
    }
    if let Ok(executable) = std::env::current_exe() {
        if let Some(parent) = executable.parent() {
            paths.insert(0, parent.join("libBadAppleBridge.dylib"));
        }
    }
    paths
}

fn load_bridge_symbols() -> Result<BridgeSymbols, AneCoreError> {
    let mut failures = Vec::new();
    for path in bridge_paths() {
        if !path.exists() {
            continue;
        }
        let library = match unsafe { Library::new(&path) } {
            Ok(library) => library,
            Err(error) => {
                failures.push(format!("{}: {error}", path.display()));
                continue;
            }
        };
        unsafe {
            let create = library.get::<CreateFn>(b"bad_apple_ane_create\0");
            let destroy = library.get::<DestroyFn>(b"bad_apple_ane_destroy\0");
            let predict = library.get::<PredictFn>(b"bad_apple_ane_predict_next\0");
            let reset = library.get::<ResetFn>(b"bad_apple_ane_reset\0");
            let prewarm = library.get::<PrewarmFn>(b"bad_apple_ane_prewarm\0");
            let ane_ratio = library.get::<AneRatioFn>(b"bad_apple_ane_placement_ratio\0");
            let compute_units =
                library.get::<ComputeUnitsFn>(b"bad_apple_ane_compute_units_raw_value\0");
            let selection_latency =
                library.get::<SelectionLatencyFn>(b"bad_apple_ane_selection_latency_us\0");
            let artifact_ratio =
                library.get::<ArtifactRatioFn>(b"bad_apple_coreml_placement_ratio\0");
            let probe_shard = library.get::<ProbeShardFn>(b"bad_apple_ane_probe_shard\0");
            if let (
                Ok(create),
                Ok(destroy),
                Ok(predict),
                Ok(reset),
                Ok(prewarm),
                Ok(ane_ratio),
                Ok(compute_units),
                Ok(selection_latency),
                Ok(artifact_ratio),
                Ok(probe_shard),
            ) = (
                create,
                destroy,
                predict,
                reset,
                prewarm,
                ane_ratio,
                compute_units,
                selection_latency,
                artifact_ratio,
                probe_shard,
            ) {
                let symbols = BridgeSymbols {
                    create: *create,
                    destroy: *destroy,
                    predict: *predict,
                    reset: *reset,
                    prewarm: *prewarm,
                    ane_ratio: *ane_ratio,
                    compute_units: *compute_units,
                    selection_latency: *selection_latency,
                    artifact_ratio: *artifact_ratio,
                    probe_shard: *probe_shard,
                    library,
                };
                return Ok(symbols);
            }
        }
        failures.push(format!("{}: missing ANE symbols", path.display()));
    }
    Err(AneCoreError::Bridge(if failures.is_empty() {
        "no in-process bridge dylib found".to_string()
    } else {
        failures.join("; ")
    }))
}

pub fn audit_artifact_placement(
    path: &Path,
    compute_units_raw_value: i32,
) -> Result<f64, AneCoreError> {
    let symbols = load_bridge_symbols()?;
    let path = CString::new(path.to_string_lossy().as_bytes())
        .map_err(|error| AneCoreError::Bridge(error.to_string()))?;
    let ratio = unsafe { (symbols.artifact_ratio)(path.as_ptr(), compute_units_raw_value) };
    if ratio < 0.0 {
        Err(AneCoreError::Bridge(
            "CoreML placement audit failed".to_string(),
        ))
    } else {
        Ok(ratio)
    }
}

pub fn probe_compiled_shard(
    path: &Path,
    compute_units_raw_value: i32,
    iterations: usize,
) -> Result<u64, AneCoreError> {
    let symbols = load_bridge_symbols()?;
    let path = CString::new(path.to_string_lossy().as_bytes())
        .map_err(|error| AneCoreError::Bridge(error.to_string()))?;
    let mut average_latency_us = 0;
    let succeeded = unsafe {
        (symbols.probe_shard)(
            path.as_ptr(),
            compute_units_raw_value,
            iterations.max(1),
            &mut average_latency_us,
        )
    };
    if succeeded {
        Ok(average_latency_us)
    } else {
        Err(AneCoreError::Prediction)
    }
}

static CONFIG: OnceLock<AneCoreConfig> = OnceLock::new();
static ENGINE: Mutex<Option<AneCore>> = Mutex::new(None);
static LAST_TOKEN_LATENCY_US: AtomicU64 = AtomicU64::new(0);
static FIRST_TOKEN_LATENCY_US: AtomicU64 = AtomicU64::new(0);
static TOKEN_COUNT: AtomicU64 = AtomicU64::new(0);
static PREDICTION_FAILURES: AtomicU64 = AtomicU64::new(0);
static CONTEXT_LIMIT: AtomicU64 = AtomicU64::new(2048);

fn with_engine<T, F>(f: F) -> Option<T>
where
    F: FnOnce(&mut AneCore) -> T,
{
    let mut guard = ENGINE.lock().ok()?;
    guard.as_mut().map(f)
}

fn with_engine_result<T, F>(f: F) -> Result<T, AneCoreError>
where
    F: FnOnce(&mut AneCore) -> Result<T, AneCoreError>,
{
    let mut guard = ENGINE
        .lock()
        .map_err(|error| AneCoreError::Bridge(error.to_string()))?;
    let engine = guard.as_mut().ok_or(AneCoreError::Unconfigured)?;
    f(engine)
}

pub fn initialize_from_env() -> Result<(), AneCoreError> {
    let config = AneCoreConfig::from_env().ok_or(AneCoreError::Unconfigured)?;
    CONFIG
        .set(config.clone())
        .map_err(|_| AneCoreError::Bridge("ANE config already initialized".to_string()))?;
    let mut engine = ENGINE
        .lock()
        .map_err(|e| AneCoreError::Bridge(e.to_string()))?;
    *engine = Some(AneCore::load(&config)?);
    Ok(())
}

pub fn is_available() -> bool {
    ENGINE.lock().ok().is_some_and(|guard| guard.is_some())
}

pub fn prewarm() -> bool {
    with_engine_result(|engine| Ok(engine.prewarm())).unwrap_or(false)
}

pub fn set_context_limit(context_limit: usize) {
    CONTEXT_LIMIT.store(context_limit.max(1) as u64, Ordering::Relaxed);
}

pub fn context_limit() -> usize {
    CONTEXT_LIMIT.load(Ordering::Relaxed) as usize
}

/// Raw token count for a prompt, used for context-window bucket selection.
/// This intentionally does not apply the chat template (which adds only a few
/// tokens) so it can run before a model bucket is loaded.
fn raw_token_count_for(config: &AneCoreConfig, prompt: &str) -> Result<usize, AneCoreError> {
    let tokenizer = Tokenizer::from_file(&config.tokenizer_path)
        .map_err(|error| AneCoreError::Tokenizer(error.to_string()))?;
    let encoding = tokenizer
        .encode(prompt, false)
        .map_err(|error| AneCoreError::Tokenizer(error.to_string()))?;
    Ok(encoding.get_ids().len())
}

/// Load the smallest configured model bucket that can hold `token_count`
/// positions. If the engine already holds that bucket, return it; otherwise
/// drop the current model and load the correct one.
fn ensure_engine_for(
    token_count: usize,
) -> Result<std::sync::MutexGuard<'static, Option<AneCore>>, AneCoreError> {
    let config = CONFIG.get().ok_or(AneCoreError::Unconfigured)?;
    let (target_seq_len, target_path) = config
        .bucket_for(token_count)
        .ok_or(AneCoreError::Unconfigured)?;

    let mut guard = ENGINE
        .lock()
        .map_err(|error| AneCoreError::Bridge(error.to_string()))?;

    let needs_load = guard
        .as_ref()
        .is_none_or(|engine| engine.seq_len != target_seq_len);

    if needs_load {
        let bucket_config = AneCoreConfig {
            model_path: target_path.to_path_buf(),
            ..config.clone()
        };
        // Drop the old model before loading the new one to free UMA resident
        // memory and avoid holding two complete compiled models at once.
        *guard = None;
        *guard = Some(AneCore::load(&bucket_config)?);
        if let Some(ref mut engine) = *guard {
            engine.prewarm();
        }
    }

    Ok(guard)
}

pub fn generate_sync(
    prompt: &str,
    max_new_tokens: usize,
    context_limit: usize,
) -> Result<String, AneCoreError> {
    generate_with_system(prompt, None, max_new_tokens, context_limit)
}

pub fn generate_with_system(
    prompt: &str,
    system: Option<&str>,
    max_new_tokens: usize,
    context_limit: usize,
) -> Result<String, AneCoreError> {
    let config = CONFIG.get().ok_or(AneCoreError::Unconfigured)?;
    let raw_tokens = raw_token_count_for(config, prompt)?;
    let total = raw_tokens + max_new_tokens;
    elevate_thread_qos();
    let mut guard = ensure_engine_for(total)?;
    let engine = guard.as_mut().ok_or(AneCoreError::Unconfigured)?;
    engine.generate(prompt, system, max_new_tokens, context_limit)
}

pub fn generate_streaming<F>(
    prompt: &str,
    max_new_tokens: usize,
    context_limit: usize,
    on_token: F,
) -> Result<String, AneCoreError>
where
    F: FnMut(&str) -> bool,
{
    let config = CONFIG.get().ok_or(AneCoreError::Unconfigured)?;
    let raw_tokens = raw_token_count_for(config, prompt)?;
    let total = raw_tokens + max_new_tokens;
    elevate_thread_qos();
    let mut guard = ensure_engine_for(total)?;
    let engine = guard.as_mut().ok_or(AneCoreError::Unconfigured)?;
    engine.generate_streaming(prompt, None, max_new_tokens, context_limit, on_token)
}

pub fn placement_ratio() -> Option<f64> {
    with_engine(|engine| engine.ane_placement_ratio())
}

pub fn compute_units_raw_value() -> Option<i32> {
    with_engine(|engine| engine.compute_units_raw_value())
}

pub fn selection_latency_us() -> Option<(u64, u64)> {
    with_engine(|engine| engine.selection_latency_us())?
}

pub fn metrics() -> (u64, u64, u64) {
    (
        LAST_TOKEN_LATENCY_US.load(Ordering::Relaxed),
        TOKEN_COUNT.load(Ordering::Relaxed),
        PREDICTION_FAILURES.load(Ordering::Relaxed),
    )
}

pub fn first_token_latency_us() -> u64 {
    FIRST_TOKEN_LATENCY_US.load(Ordering::Relaxed)
}

pub fn reset_counters() {
    LAST_TOKEN_LATENCY_US.store(0, Ordering::Relaxed);
    FIRST_TOKEN_LATENCY_US.store(0, Ordering::Relaxed);
    TOKEN_COUNT.store(0, Ordering::Relaxed);
    PREDICTION_FAILURES.store(0, Ordering::Relaxed);
}

/// Live decode vitals for the Bad Apple boot banner.
/// Returns `(prewarm_latency_us, avg_token_latency_us, tokens_per_second)`.
/// `elapsed_us` is the wall time the caller measured around `generate_sync`.
pub fn decode_vitals(elapsed_us: u64) -> (u64, u64, f64) {
    let (last_token_us, token_count, _) = metrics();
    let first_token_us = first_token_latency_us();
    let prewarm_us = selection_latency_us()
        .map(|(_, prewarm)| prewarm)
        .unwrap_or(0);
    let avg_decode_us = if token_count > 1 {
        elapsed_us.saturating_sub(first_token_us) / (token_count - 1)
    } else {
        last_token_us
    };
    let tokens_per_second = if avg_decode_us > 0 {
        1_000_000.0 / avg_decode_us as f64
    } else {
        0.0
    };
    (prewarm_us, avg_decode_us, tokens_per_second)
}

pub fn artifact_is_compiled_model(path: &Path) -> bool {
    path.is_dir()
        && path
            .extension()
            .is_some_and(|extension| extension == "mlmodelc")
}

#[cfg(target_os = "macos")]
extern "C" {
    /// Set the current thread's QoS class. Only available on Apple OSs.
    fn pthread_set_qos_class_self_np(qos_class: u32, relative_priority: i32) -> i32;
}

#[cfg(target_os = "macos")]
const QOS_CLASS_USER_INTERACTIVE: u32 = 0x21;

/// Elevate the calling thread to the highest scheduling class.
/// This is a no-op on non-macOS targets and on threads where the override is
/// not permitted by the runtime. It does not lock memory bus lines.
fn elevate_thread_qos() {
    #[cfg(target_os = "macos")]
    unsafe {
        let result = pthread_set_qos_class_self_np(QOS_CLASS_USER_INTERACTIVE, 0);
        if result != 0 {
            tracing::debug!("pthread_set_qos_class_self_np returned {}", result);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn low_power_policy_reduces_context_and_suppresses_prewarm() {
        let input = AneGovernorInput {
            critic_score: 0.2,
            previous_critic_score: 0.8,
            average_loss: 4.61,
            battery_percent: 10.0,
            battery_charging: false,
            photons: 0.0,
            ..AneGovernorInput::default()
        };
        let decision = governor_decision(input);
        assert_eq!(decision.max_context_tokens, 512);
        assert_eq!(decision.priority, AneExecutionPriority::Utility);
        assert!(!decision.should_prewarm);
    }

    #[test]
    fn falling_confidence_prewarms_when_resources_allow() {
        let input = AneGovernorInput {
            critic_score: 0.5,
            previous_critic_score: 0.8,
            average_loss: 4.61,
            battery_percent: 80.0,
            battery_charging: true,
            photons: 1.0,
            memory_pressure_percent: 20.0,
        };
        let decision = governor_decision(input);
        assert_eq!(decision.max_context_tokens, 2048);
        assert_eq!(decision.priority, AneExecutionPriority::UserInitiated);
        assert!(decision.should_prewarm);
    }

    #[test]
    fn missing_configuration_is_unavailable() {
        if AneCoreConfig::from_env().is_none() {
            assert!(!is_available());
        }
    }

    #[test]
    fn qwen_fallback_renders_roles_and_generation_prompt() {
        let rendered = render_qwen_chat("who are you?", None);
        assert!(rendered.contains("<|im_start|>system\nYou are Bad Apple"));
        assert!(rendered.contains("<|im_start|>user\nwho are you?\n/no_think<|im_end|>"));
        assert!(rendered.ends_with("<|im_start|>assistant\n<think>\n\n</think>\n\n"));
    }
}
