use serde::{Serialize, Deserialize};
use hmac::{Hmac, Mac, KeyInit};
use sha2::Sha256;
use base64::{Engine, engine::general_purpose::STANDARD};
use sysinfo::System;

/// Compact engram payload for UDP exchange: excludes the large 2048-D embedding,
/// which can be regenerated by the receiver, but carries the sender's brain state
/// for vector exchange.
#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct CompactEngramPacket {
    pub id: u64,
    pub timestamp: u64,
    pub experiential_text: String,
    pub emotional_state_snapshot: String,
    pub origin_instance: String,
    pub brain_state: Vec<f64>,
}

/// Signed UDP envelope for multi-agent engram exchange.
/// Uses HMAC-SHA256 for integrity and base64 for compact binary-safe encoding.
#[derive(Serialize, Deserialize, Clone, Debug)]
pub struct SignedUdpPacket {
    pub sender: String,
    pub payload_b64: String,
    pub signature_hex: String,
}

/// Resolve a shared multi-agent signing secret.
/// Prefer the `MULTI_AGENT_SECRET` environment variable; otherwise derive a
/// default from the local hostname.  This keeps shared secrets out of source.
pub fn multi_agent_secret() -> Vec<u8> {
    let host = System::host_name().unwrap_or_else(|| "localhost".to_string());
    std::env::var("MULTI_AGENT_SECRET")
        .unwrap_or_else(|_| format!("firefly-{}-default", host))
        .into_bytes()
}

fn hmac_sha256(key: &[u8], data: &[u8]) -> Vec<u8> {
    type HmacSha256 = Hmac<Sha256>;
    let mut mac = HmacSha256::new_from_slice(key).expect("HMAC accepts any key length");
    mac.update(data);
    mac.finalize().into_bytes().as_slice().to_vec()
}

fn hex_encode(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{:02x}", b)).collect()
}

/// Sign a compact engram payload, returning a JSON-safe signed packet.
pub fn sign_packet(sender: &str, payload: &[u8], secret: &[u8]) -> SignedUdpPacket {
    let signature = hex_encode(&hmac_sha256(secret, payload));
    SignedUdpPacket {
        sender: sender.to_string(),
        payload_b64: STANDARD.encode(payload),
        signature_hex: signature,
    }
}

/// Decode the base64 payload of a signed packet (does not verify integrity).
pub fn decode_payload(packet: &SignedUdpPacket) -> Option<Vec<u8>> {
    STANDARD.decode(&packet.payload_b64).ok()
}

/// Verify the HMAC-SHA256 signature of a signed packet.
pub fn verify_packet(packet: &SignedUdpPacket, secret: &[u8]) -> bool {
    let Some(payload) = decode_payload(packet) else {
        return false;
    };
    let expected = hex_encode(&hmac_sha256(secret, &payload));
    expected == packet.signature_hex
}
